### ISSUE TITLE
Marko example not working

### ISSUE THREAD

**Issue by Niputi** [hapijs/vision#126]
I downloaded the repository, added `host: "localhost"` in the server.connection and edited `const Vision = require('../..');` to `const Vision = require('vision');` since `../..` could not be found

I ran the marko example with the command `node examples/marko/index`

I get the below error message when I visit the localhost url
> Debug: internal, implementation, error
    TypeError: "string" must be a string, Buffer, or ArrayBuffer
    at Function.byteLength (buffer.js:477:11)
    at internals.Response.Payload.internals.Payload.internals.Payload.size (C:\Users\peter\Desktop\vision-master\node_modules\hapi\lib\response.js:702:70)
    at response._marshal (C:\Users\peter\Desktop\vision-master\node_modules\hapi\lib\transmit.js:97:70)
    at module.exports.internals.Response.internals.Response._streamify (C:\Users\peter\Desktop\vision-master\node_modules\hapi\lib\response.js:622:12)
    at _processors.marshal (C:\Users\peter\Desktop\vision-master\node_modules\hapi\lib\response.js:567:21)
    at manager._render (C:\Users\peter\Desktop\vision-master\node_modules\vision\lib\manager.js:591:16)
    at compiled.template (C:\Users\peter\Desktop\vision-master\node_modules\vision\lib\manager.js:498:20)
    at Object.renderer [as template] (C:\Users\peter\Desktop\vision-master\node_modules\vision\lib\manager.js:147:28)
    at module.exports.internals.Manager.internals.Manager._render (C:\Users\peter\Desktop\vision-master\node_modules\vision\lib\manager.js:489:14)
    at Object.internals.marshal (C:\Users\peter\Desktop\vision-master\node_modules\vision\lib\manager.js:577:13)

**Comment by wswoodruff** [comment]
@Niputi What version of `Marko` are you using? If 4.x this should be solved by #111

**Comment by Niputi** [comment]
@wswoodruff I can't remember since it's a long time ago but I can say that I just tried to download version 3.0.0, 4.0.0, 5.0.0, 5.1.0 and the master, run different examples by doing `npm i` and `node examples/marko/index`, I also tried `node examples/handlebars/index`.  All of them said `server.connection is not a function`
With the 5.1.0 version, I tried to change hapi version to v16 on Cannot read property 'register' of undefined and devDependencies. The error message changed to `Cannot read property 'register' of undefined`.
I also tried the fork in #111, that also gave `server.connection is not a function` but when change the hapi version v16 it gave me `Cannot read property 'register' of undefined`. 
What I can conclude from this is that the hapi version is wrong and something else or I'm doing something wrong

**Comment by wswoodruff** [comment]
@Niputi It's possible there's another hapi module you're using that isn't compatible with `hapi v17` -- making that call to `server.connection`. -- That's a telltale sign that something you're using hasn't been upgraded, there aren't any calls to server.connection here so time to search it out 🔎 =P

**Comment by wswoodruff** [comment]
@Niputi Update: I read your response incorrectly, It's on ME to update the tests and examples. Expect that to be coming up this week!

**Comment by wswoodruff** [comment]
@Niputi I just updated the marko example and the README, you should be able to get it working by running `node examples/marko` -- all of the examples have been updated to hapi v17 now 👍

**Comment by Niputi** [comment]
@wswoodruff thanks for the update. When I did `npm i` there were two warnings which said `hapi-react-views require a peer`, should those warnings be there? The marko example is now working. I tried to run all the other examples and they all worked, so that's nice.
on another topic shouldn't the new readme say that this package version is for hapi v17+?

**Comment by wswoodruff** [comment]
@Niputi Glad to hear you confirm the examples work for you! I just submitted [this issue](https://github.com/jedireza/hapi-react-views/issues/71) on `hapi-react-views` to upgrade to react v16, which I use in the jsx example. Vision itself would not require react because it's only used in the example.

**Comment by wswoodruff** [comment]
I added a note about hapi v17 in the docs -- thanks for working this out with me!

**Comment by wswoodruff** [comment]
@Niputi the `hapi-react-views` maintainer updated it to React 16 https://github.com/jedireza/hapi-react-views/blob/master/package.json#L34-L35

You shouldn't receive those warnings anymore
