### ISSUE TITLE
Handlebars partial path not found

### ISSUE THREAD

**Issue by constashare** [hapijs/vision#149]
I've tried to figure this out but I can't, the paths are correct so I'm not sure what the issue. Here is my vision options configure:

options: {
                    engines: {
                        html: Handlebars.create()
                    },
                    relativeTo: __dirname,
                    path: './server/resources/views',
                    layout: true,
                    layoutPath: './server/resources/layouts',
                    layoutKeyword: 'layout',
                    partialsPath: 'server/resources/partials',
                    helpersPath: './server/resources/helpers',
}

I'm using {{> navbar }} in the html template
And here is the error log:

error: The partial navbar could not be found: The partial navbar could not be found
    at Object.invokePartial (\node_modules\handlebars\dist\cjs\handlebars\runtime.js:281:11)
    at Object.invokePartialWrapper [as invokePartial] (\node_modules\handlebars\dist\cjs\handlebars\runtime.js:68:39)
    at Object.eval [as main] (eval at createFunctionContext (\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:6:28)
    at main (\node_modules\handlebars\dist\cjs\handlebars\runtime.js:175:32)
    at ret (\node_modules\handlebars\dist\cjs\handlebars\runtime.js:178:12)
    at ret (\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:526:21)
    at Object.renderer [as layout] (\node_modules\vision\lib\manager.js:140:36)
    at compiled.template (\node_modules\vision\lib\manager.js:513:18)
    at Object.renderer [as template] (\node_modules\vision\lib\manager.js:146:28)
    at module.exports.internals.Manager.internals.Manager._render (\node_modules\vision\lib\manager.js:498:14)
180602/071213.517, (1527923533517:Vaugnsha:6800:jhx27qyn:10000) [error] message: The partial navbar could not be found: The partial navbar could not be found, stack: Error: The partial navbar could not be found: The partial navbar could not be found
    at Object.invokePartial (\node_modules\handlebars\dist\cjs\handlebars\runtime.js:281:11)
    at Object.invokePartialWrapper [as invokePartial] (\node_modules\handlebars\dist\cjs\handlebars\runtime.js:68:39)
    at Object.eval [as main] (eval at createFunctionContext (\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:6:28)
    at main (\node_modules\handlebars\dist\cjs\handlebars\runtime.js:175:32)
    at ret (\node_modules\handlebars\dist\cjs\handlebars\runtime.js:178:12)
    at ret (\frame\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:526:21)
    at Object.renderer [as layout] (\node_modules\vision\lib\manager.js:140:36)
    at compiled.template (\node_modules\vision\lib\manager.js:513:18)
    at Object.renderer [as template] (\node_modules\vision\lib\manager.js:146:28)
    at module.exports.internals.Manager.internals.Manager._render (\node_modules\vision\lib\manager.js:498:14)

Any idea what I'm doing wrong?

**Comment by wswoodruff** [comment]
@constashare Are you missing a `./` at the beginning of your partials path?

**Comment by constashare** [comment]
@wswoodruff I've tried both with and without and the runtime error is still saying no partial found.

**Comment by wswoodruff** [comment]
@constashare Are you able to link to your project or provide some more context?

I was digging around looking for similar issues with Vision in the past, it seems that there were issues with partials when working on `windows` -- do you have access to a linux-ish environment like Mac to try this out on?

**Comment by wswoodruff** [comment]
@constashare Did you figure out the issue? If you give me some more info on your project I can help some more

**Comment by constashare** [comment]
@wswoodruff  It's OK I switched to jsx/react but I can't get any functions to work.

**Comment by wswoodruff** [comment]
@constashare Are you using `hapi-react-views`?
There's an example of usage with vision at https://github.com/hapijs/vision/tree/master/examples/jsx

Let me know if you still have problems after checking out that example =)

**Comment by constashare** [comment]
@wswoodruff I am using hapi-react-views. But the function onClick doesn't do anything I can try reinstalling the app

**Comment by constashare** [comment]
@wswoodruff  it could probably I have to install peer dependencies myself

**Comment by constashare** [comment]
@wswoodruff  still nothing is firing

**Comment by wswoodruff** [comment]
@constashare Can you do me a favor and run the example I linked? You can run it locally by cloning vision locally, running npm install, and running `node examples/jsx`? See if you can add an onClick() handler in there and see if you run into the same issues

**Comment by constashare** [comment]
@wswoodruff I ran jsx in vision clone and onClick() still didn't fire anything. I used the props method and regular function call. When I used onClick={this.handleClick} I received nothing but when I did onClick={this.handleClick()} I got a even firing.

**Comment by constashare** [comment]
@wswoodruff if I'm not mistaking onClick={this.handleClick}  is the proper way, but that never worked.

**Comment by wswoodruff** [comment]
@constashare So at least we've ruled out your setup as the problem, not sure what's happening with the click handlers yet though

**Comment by wswoodruff** [comment]
@constashare I'm going to close this issue as it's become a different one. If there are still issues getting click handlers to work properly we can continue discussion on the `hapi-react-views` repo

**Comment by wswoodruff** [comment]
@constashare back to the original issue, can you turn off `All Exceptions` in your VS Code debugger like you see in this pic? 
![b4d94908-27fc-11e6-981e-2bf39907493e](https://user-images.githubusercontent.com/9013245/41493522-0ed1c222-70d6-11e8-9f3a-80edd70eae21.png)

**Comment by wswoodruff** [comment]
Then try it again, I'm suspicious of VS Code now and working with Microsoft && Node && npm together -- I keep seeming to come across Microsoft and / or VS Code related issues here and there in the Node community lately
