### ISSUE TITLE
Twig Cannot extend an inline template

### ISSUE THREAD

**Issue by mitjafelicijan** [hapijs/vision#195]
I have been trying to use extends functionality for Twig and cannot get it to work regardless of what I do. I have managed to make `includes` working properly but not `extends`.

This is my server code.

```js
server.views({
  engines: {
    twig: {
      compile: (src, options) => {
        const template = Twig.twig({
          id: options.filename,
          data: src,
          allowInlineIncludes: true,
          strictVariables: true,
        });
        return (context) => template.render(context);
      },
    },
  },
  relativeTo: __dirname,
  path: ['modules', 'shared'],
});
```
When I am trying to include a partial Iit works like intended.

```twig
{% include "shared/navigation.twig" with {'foo': 'bar'} only %}`
```

But if I try to use extends option I get the following error.

```twig
{% extends "shared/base/default.twig" %}

{% block main %}
{% endblock %}
```

```
Debug: internal, implementation, error 
    Error: Cannot extend an inline template.
    at /home/m/Dropbox/projects/.../node_modules/@hapi/vision/lib/manager.js:413:33
    at Object.renderer [as template] (/home/m/Dropbox/projects/.../node_modules/@hapi/vision/lib/manager.js:106:36)
    at /home/m/Dropbox/projects/.../node_modules/@hapi/vision/lib/manager.js:410:22
    at new Promise (<anonymous>)
    at Manager._render (/home/m/Dropbox/projects/.../node_modules/@hapi/vision/lib/manager.js:408:16)
    at Object.internals.marshal (/home/m/Dropbox/projects/.../node_modules/@hapi/vision/lib/manager.js:545:36)
    at module.exports.internals.Response._marshal (/home/m/Dropbox/projects/.../node_modules/@hapi/hapi/lib/response.js:539:49)
    at exports.content (/home/m/Dropbox/projects/.../node_modules/@hapi/hapi/lib/headers.js:43:24)
    at Object.internals.marshal (/home/m/Dropbox/.../node_modules/@hapi/hapi/lib/transmit.js:43:15)
    at async Object.exports.send (/home/m/Dropbox/.../node_modules/@hapi/hapi/lib/transmit.js:29:9)
```

I really am out of ideas here.

Thanks in advance ...

**Comment by hueniverse** [comment]
Unfortunately, no community resources were available to help resolve this issue after two weeks, and it is being closed. We close unresolved community issues to keep the issue tracker organized and effective. Please check https://hapi.dev/support for other support options.
