### ISSUE TITLE
TypeError: Cannot read property '_render' of undefined

### ISSUE THREAD

**Issue by ryanwalters** [hapijs/vision#85]
```
hapi@13.4.0
inert@3.2.1
vision@4.1.0
```

While trying to use `hapi-swagger@5.1.0` I receive this error when hitting the `/documentation` endpoint:

```
11:14:20 web.1  |     TypeError: Cannot read property '_render' of undefined
11:14:20 web.1  |     at Object.internals.marshal (...\node_modules\vision\lib\manager.js:583:12)
11:14:20 web.1  |     at internals.Response._marshal (...\node_modules\hapi\lib\response.js:473:22)
11:14:20 web.1  |     at internals.state (...\node_modules\hapi\lib\transmit.js:124:18)
11:14:20 web.1  |     at Items.parallel (...\node_modules\hapi\lib\transmit.js:509:20)
11:14:20 web.1  |     at done (...\node_modules\hapi\node_modules\items\lib\index.js:63:25)
11:14:20 web.1  |     at each (...\node_modules\hapi\lib\transmit.js:480:20)
11:14:20 web.1  |     at Object.exports.parallel (...\node_modules\hapi\node_modules\items\lib\index.js:70:13)
11:14:20 web.1  |     at Object.internals.state (...\node_modules\hapi\lib\transmit.js:502:11)
11:14:20 web.1  |     at Object.internals.marshal (...\node_modules\hapi\lib\transmit.js:98:15)
11:14:20 web.1  |     at Object.exports.send (...\node_modules\hapi\lib\transmit.js:30:15)
```

Diving in a bit, I see that `manager._render` is failing. The `manager` object looks like this:

```
{ statusCode: 200,
  data:
   { manager: { _context: null, _engines: [Object], _defaultExtension: 'html' },
     template: 'index.html',
     context: { hapiSwagger: [Object] },
     options: undefined,
     compiled: { settings: [Object], template: [Function] } } }
```

I'm new to vision, so I'm not sure what is causing this issue but figured I'd post here in case it is a bug.

Let me know if you need any further information.

**Comment by ryanwalters** [comment]
This was caused by modification to the response in the `onPreResponse` extension point, not with vision.
